project:
  type: website
  output-dir: _site

website:
  title: "Hunter Riccardelli"
  description: "PhD Candidate in Applied Economics, Oregon State University"
  favicon: files/favicon.ico


  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: files/cv.pdf
      - text: "Teaching"
        href: teaching.qmd
    right:
      - icon: envelope
        href: mailto:riccardh@oregonstate.edu
        aria-label: Email

  page-footer:
    center: "© 2026 Hunter Riccardelli"

format:
  html:
    theme:
      light: [flatly, custom.scss]
    css: custom.scss
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 900px
      margin-width: 200px
