---
title: "Research"
---

## Job Market Paper

**The Impact of Refugee Arrivals on Food Security, Income, and Crop Prices in Rural Uganda**  
*Under Review, Economic Development and Cultural Change*

::: {.abstract-block}
[Abstract]{.abstract-label} 

::: {.abstract-text}
This study estimates the impacts of refugee inflows on household food security and agricultural production in Uganda. Using a representative panel of data on refugees and hosts from 2017–2021, I find that refugee arrivals cause statistically significant food security deterioration. Scaled to average annual arrivals (9,182), host households experience a 9.1-point (0.55 SD) increase in the Coping Strategies Indexand established refugees an 11.4-point (0.44 SD) increase. These impacts push the average householdinto the bottom quartile of baseline food security, driven primarily by net consumer host households andnet producer refugee households. Despite adverse consumption effects, agricultural market participation expands: host and established refugee households are 26.6 and 11.2 percentage points more likely to report agricultural earnings, respectively. For host households, this market entry is coupled with asignificant accumulation of livestock, evidenced by a 68 percent increase in total holdings over 12 months. Refugee households, however, exhibit no such accumulation. The decline in food security, despite market extensification, is consistent with delayed, arrival-driven price inflation for both aid and non-aid food commodities. These price effects erode purchasing power, disproportionately harming net food consumers and households with limited production capacity or aid. These findings underscore the importance of agricultural support and targeted in-kind aid in rural refugee-hosting regions.
:::

[Paper (PDF)](https://drive.google.com/file/d/1PWbWVHN0caCz9BBkJXCLjHu_tMEl83Dg/view?usp=sharing) 
:::

---

## Working Papers

**Cultivating Self-Reliance? An Analysis of Uganda’s Refugee Land Allocation Policy**  
*with Jennifer Alix-Garcia and Jamon Van Den Hoek*  
*Submitted to PNAS*

::: {.abstract-block}
[Abstract]{.abstract-label} 

::: {.abstract-text}
This paper examines the impact of Uganda’s “self-reliance” policy for refugees, which includes allocating land to new refugee arrivals with the intention of reducing household reliance on international aid. Using household survey data covering 9 settlements from 2017 to 2021, along with statistical methods to circumvent bias in the estimation, we estimate the effect of land allocations upon arrival on household food security and agricultural production outcomes. We find that only 40 percent of refugee households actually receive a land allocation greater than or equal to 0.25 acres upon arrival at a settlement. Our estimations show that larger initial land allocations are associated with higher food security, greater propensity to harvest and to have any agricultural earnings, more land under cultivation, and a higher likelihood of having any livestock. However, we also demonstrate that in order to improve refugee outcomes so that they are similar to the surrounding host communities, refugee land allocation would have to rise from 0.25 acres to 1.84 acres. This level of land transfer would exceed the total area of land officially set aside in many refugee settlements by a substantial amount, even before taking into account variation in land quality. Qualitative interviews suggest that relatively low agricultural production among refugees may be due to the fact that many had never farmed until they arrived in Uganda, and that there is little access to agricultural inputs. We conclude that while the policy does improve refugee welfare, self-reliance through land allocation alone is insufficient without concurrent support in refugees’ agricultural capacity.
:::

[Paper (PDF)](https://drive.google.com/file/d/1ywf9iwUwM67k2Rcv-JbceEENNSq-J_ej/view?usp=sharing)
:::

---

## Work in Progress

- **Aid Modalities and Land Use Dynamics Around Refugee Settlements in Uganda**    
*In Development*

- **Living Income Differential and Smallholder Welfare in West African Cocoa Markets**    
*In Development*

---
